### ISSUE TITLE
can u tell differece between toriptables3 and toriptables2? Thanks a lot for script

### ISSUE THREAD

**Issue by cl0wn420** [ruped24/toriptables3#1]
can u tell differece between toriptables3 and toriptables2? Thanks a lot for script

**Comment by ruped24** [comment]
> can u tell differece between toriptables3 and toriptables2? Thanks a lot for script

Good question:

Functionally, no difference.

- [Python 2.7 support will be remove from Debian](https://forums.debian.net/viewtopic.php?t=144859) ([kali's upstream](https://www.kali.org/blog/python-2-end-of-life/)).
- toriptables2.py is written in Python version 2.7. It's now Legacy -> [EOL](https://www.python.org/doc/sunset-python-2/) 
- toriptables3.py is written for Python version 3.8.2 => - [Future](https://www.python.org/downloads/)
- [toriptables2](https://github.com/ruped24/toriptables2/releases/tag/2-2.1) ELF executes independent of Python ->  No Python! :smile:

**Update:** Also see [toriptables3](https://github.com/ruped24/toriptables3/releases/tag/v3.0) ELF **one file** [AppImage](https://appimage.org/) -> No Python!! :open_mouth: 

I hope I made it clear... Let me know if you have any further questions. For more information see [FAQ](https://github.com/ruped24/toriptables2/wiki/Troubleshooting#frequently-asked-questions).

**Comment by ruped24** [comment]
> Everything _used to work fine_, now it can't connect to the Tor network:

Try: 

1. sudo toriptables3.py -f
2. toriptables3.py -i

See [Troubleshooting](https://github.com/ruped24/toriptables2/wiki/Troubleshooting).

**Comment by sigizmyndaristarhovich** [comment]
Most likely, my provider is blocking the tor network, because it turns out to connect via VPN.

**Comment by ruped24** [comment]
> Most likely, my provider is blocking the tor network, because it turns out to connect via VPN.

Try:

Connect to your VPN provider, then try to connect to Tor Network.
This works for me. VPN --> Toriptables.

Let me know...

**Comment by sigizmyndaristarhovich** [comment]
sudo autovpn2                                                                          

[autovpn2] getting server list
[autovpn2] parsing response
[autovpn2] looking for US
Traceback (most recent call last):
  File "/usr/local/bin/autovpn2", line 84, in <module>
    AutoVpn("".join(argv[1:]))
  File "/usr/local/bin/autovpn2", line 24, in __init__
    self.get_serverlist()
  File "/usr/local/bin/autovpn2", line 49, in get_serverlist
    urlopen("https://www.vpngate.net/api/iphone/")
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1248, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1205, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 104] Connection reset by peer>
