### ISSUE TITLE
What rule should be added to route traffic comming from a virtual interface through Tor?

### ISSUE THREAD

**Issue by jefazo92** [ruped24/toriptables3#3]
Hi @ruped24, I have configured a virtual interface (vboxnet0) for a VM. I have program sniffing the VM traffic as goes through vboxnet0. I'd like to route the network traffic through this interface and, as traffic leaves the interface, be routed by the Tor protocol. I have run your script and tried to add my own rules to have Tor route the VM's traffic. Tor is enabled on host but it doesn't for my VM (which is still using my public ip address). I would really appreciate it if you could let me know how to modify the rules accordingly to allow my VM traffic to go through Tor as it leaves vboxnet0.

**Comment by ruped24** [comment]
>  I have run your script and tried to add my own rules to have Tor route the VM's traffic. 

Unfortunately, your request falls outside of our area of expertise.
