### ISSUE TITLE
Cloudflare detecting "suspicious traffic"

### ISSUE THREAD

**Issue by shivagnihotri** [ruped24/toriptables3#4]
Greetings from Paraguay, @ruped24! ;-)

I am a German currently working in Paraguay and a long-term user of your wonderful script, piping it through my ParrotOS every single day. Since I am using my machine to work with over here, I need to access websites such as [monday.com](https://monday.com), which seem to have an issue with the "suspicious" traffic when using toriptables3 and thus I cannot login.

Flushing the iptables does not do good either, because then I cannot access the internet at all. Somehow I only get connected to the web using your script - which is fine for me. Is there a way you could enhance your script by making it more obduscated for Cloudflare and other "traffic sniffers" so that connections pass through more smoothly?

Also, you should pin toriptables3 and unpin toriptables2 on your account here on GitHub. :) Have a wonderful day! :sun_with_face:

**Comment by ruped24** [comment]
>Is there a way you could enhance your script by making it more obduscated for Cloudflare and other "traffic sniffers" so that connections pass through more smoothly?

All the script does it put you on the Tor network, then gets out of the way. Some countries will/are blocking at their edge routers.

**Comment by shivagnihotri** [comment]
Vielen Dank. Would you recommend me to use the script or the AppImage for my ParrotOS?

**Comment by ruped24** [comment]
> 



> Vielen Dank. Would you recommend me to use the script or the AppImage for my ParrotOS?

The AppImages will run on any .deb  machine with out installing or a python interpreter.  With the AppImages, you can try it -before you buy it.  If it works fine, if not delete it.  Very noob friendly.

**Comment by 0x41337** [comment]
@shivagnihotri 

You can pass your traffic from the tor exit node through a proxy to mask that you are using Tor.

Works well for accessing clearnet. But be careful, use a good proxy to avoid being blocked by destination, in preference to residential proxies.
