### ISSUE TITLE
[Feature Request] Automatic Tor Proxy Rotation

### ISSUE THREAD

**Issue by shivagnihotri** [ruped24/toriptables3#5]
![Monday](https://user-images.githubusercontent.com/97066277/197028567-a04d6525-82e0-4dba-a282-86a402837162.png)
Good evening @ruped24, in relation and the hope to solve my Issues with Issue #4 I would like to suggest an improvement of your script to automatically rotate Tor proxies. The thing is, I have no outgoing internet connection without running toriptables and would love that toriptables automatically starts on system startup and to smoothly rotate proxies to allow [hcaptcha](https://www.hcaptcha.com) bypass. Maybe you can use the code of [dockertor](https://github.com/donspablo/dockertor), [scrapy-tor-proxy-rotation](https://github.com/elvesrodrigues/scrapy-tor-proxy-rotation) or [tor-proxy-rotator](https://github.com/noma4i/tor-proxy-rotator) to achieve this. Other solutions on how to auto-run your script and solve the captcha issue are appreciated.

**Comment by ruped24** [comment]
> Good evening @ruped24, in relation and the hope to solve my Issues with Issue #4 I would like to suggest an improvement of your script to automatically rotate Tor proxies. The thing is, I have no outgoing internet connection without running toriptables and would love that toriptables automatically starts on system startup and to smoothly rotate proxies to allow [hcaptcha](https://www.hcaptcha.com) bypass. Maybe you can use the code of [dockertor](https://github.com/donspablo/dockertor), [scrapy-tor-proxy-rotation](https://github.com/elvesrodrigues/scrapy-tor-proxy-rotation) or [tor-proxy-rotator](https://github.com/noma4i/tor-proxy-rotator) to achieve this. Other solutions on how to auto-run your script and solve the captcha issue are appreciated.

Hello:
1. I'm only doing support and accepting pull request.
2. My suggestion is to, go to Troubleshooting -> [Set Tor ExitNodes](https://github.com/ruped24/toriptables2/wiki/Troubleshooting#set-tor-exitnodes).  Set the country code to "??".
3. To rotate your country code exit nodes see. [Tor_ip_switcher](https://github.com/ruped24/tor_ip_switcher)

I hope this work.

PS.  I can't spend anymore time on this issue. Closing.
