### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by Kia-Pashang** [ruped24/toriptables3#6]
Hello , how can we make a TOR interface " tor0" that be shown in (ip a) and forward another network interface  "wg0" that is udp protocol to tor0 interface with iptables?

**Comment by ruped24** [comment]
> Hello , how can we make a TOR interface " tor0" that be shown in (ip a) and forward another network interface "wg0" that is udp protocol to tor0 interface with iptables?

Unfortunately,  I'm _only_ supplying installation support.
